apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-03-24T133148Z
  name: policy-exc-req-t7014l3420s-1
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  match:
    any: []
